FROM golang:1.12.0-alpine3.9
MAINTAINER CyberArk Software Ltd.
LABEL id="conjur-authn-k8s-client-test-runner"

ENTRYPOINT [ "go", "test", "-coverprofile=/test/c.out", "-v", "-timeout", "3m" ]
WORKDIR /conjur-authn-k8s-client

RUN apk add -u curl \
               gcc \
               git \
               mercurial \
               musl-dev

COPY go.mod go.sum /conjur-authn-k8s-client/

RUN go mod download

RUN go get -u github.com/axw/gocov/gocov && \
    go get -u github.com/AlekSi/gocov-xml
    
COPY . .
